[package]
name = "holo-pim"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
holo-northbound = { path = "../holo-northbound", features = ["pim"] }
holo-protocol = { path = "../holo-protocol" }
holo-utils = { path = "../holo-utils" }
holo-yang = { path = "../holo-yang", features = ["pim"] }
phf.workspace = true
serde.workspace = true

[lints]
workspace = true

[dev-dependencies]
yang5 = { workspace = true, features = ["bundled"] }

[build-dependencies]
holo-yang = { path = "../holo-yang", features = ["pim"] }
yang5 = { workspace = true, features = ["bundled"] }
